### ISSUE TITLE
StarMask 失败交易错误处理优化建议

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starmask-extension#51]
当前有一些情况下，交易会一直是 pending 状态，只能通过重启或者删除插件来解决。建议优化一下错误处理的机制：

1. 交易一旦生成，就应该能算出 hash，可以让用户在界面上看到 hash，这个对排查问题也很有用。不然用户反馈交易丢了，或者卡住了，但没有 hash，就很难排查是哪里的问题。
2. 提交给交易池，调用 rpc 报错，根据错误分别处理，1. 交易无法通过验证，报客户端错误，标记为失败丢弃。2. 其他错误，比如服务不可用，ratelimit 限制，网络超时等，等待一段时间后重试。
3. 如果重试超过一定的次数，则直接标记为失败（感觉也可以考虑给最新的一条失败交易增加一个人工重试的按钮？）。
4. 有了重试机制后，会有一种特殊情况需要处理：超时的情况下，有可能交易已经被提交，并且打包，这种最后需要标记为成功。

如果有错误码不明确，RPC 这边一起定义修改。

**Comment by wk3368** [comment]
问题描述：
第三方的dapp，比如Kiko的IDO，发起一个交易之后， Starmask里面的交易一直处于Pending状态，几十分钟都没变化：
![IMAGE 2022-03-06 00:42:55](https://user-images.githubusercontent.com/171268/156892279-e482e6e2-c51e-4761-b75d-a4973847358d.jpg)

导致dapp里面的状态也是一直在loading：
![IMAGE 2022-03-06 00:41:28](https://user-images.githubusercontent.com/171268/156892239-e090cee9-798a-4c4b-9da8-4624eba7d0d4.jpg)

第一行，是唤起钱包后，发出交易，返回hash，就认为是成功。如果钱包拒绝，就是失败了。
第二行，是拿到hash后，去链上查看事件，轮循查，如果状态是executed ，就认为是成功。

Root Cause：
电脑的网络出现问题（比如梯子挂了），导致Starmask发起的rpc请求都没有响应。


解决方案：
1. StarMask里面：加定时轮训，每5分钟都会去检查一下所有pending的交易，如果没有生成hash或者sequence number大于用户最新的sequence number，就直接标记为Unknown。等下一次网络正常的时候（比如重新打开StarMask）会把所有标记为Unknown的交易，重新去查询一次交易结果，根据返回修改成相应的状态（Confirmed/Failed/Dropped)
2. 第三方的Dapp里面，也需要加检查逻辑： 如果超过5分钟没有收到返回的hash 就提示交易异常

**Comment by wk3368** [comment]
> 当前有一些情况下，交易会一直是 pending 状态，只能通过重启或者删除插件来解决。建议优化一下错误处理的机制：
> 
> 1. 交易一旦生成，就应该能算出 hash，可以让用户在界面上看到 hash，这个对排查问题也很有用。不然用户反馈交易丢了，或者卡住了，但没有 hash，就很难排查是哪里的问题。

**这个hash如果有了的话，在交易详情弹窗里面是可以拷贝出来的，或者点击链接到浏览器**
<img width="347" alt="image" src="https://user-images.githubusercontent.com/171268/156892655-303d51a8-731c-4ef7-a014-7417ba0b50ae.png">

> 2. 提交给交易池，调用 rpc 报错，根据错误分别处理，1. 交易无法通过验证，报客户端错误，标记为失败丢弃。2. 其他错误，比如服务不可用，ratelimit 限制，网络超时等，等待一段时间后重试。
> 3. 如果重试超过一定的次数，则直接标记为失败（感觉也可以考虑给最新的一条失败交易增加一个人工重试的按钮？）。
> 4. 有了重试机制后，会有一种特殊情况需要处理：超时的情况下，有可能交易已经被提交，并且打包，这种最后需要标记为成功。

**2/3/4的逻辑，在StarMask里面本身就已经都有了，但是前提是网络正常的时候才会生效，如果网络都没有了（vpn挂了） 那啥都不好使。**

> 如果有错误码不明确，RPC 这边一起定义修改。
**V3.8.0的交易详情弹窗里面加了个逻辑，如果是失败的交易，最下面有个链接，点击之后可以拷贝出交易的原始信息，方便用户发给开发者进行debug**
<img width="342" alt="image" src="https://user-images.githubusercontent.com/171268/156892761-640d4e00-0111-4476-b401-25065975dd88.png">

**Comment by wk3368** [comment]
附件是一个拷贝出来的交易详情的例子：

[txn.txt](https://github.com/starcoinorg/starmask-extension/files/8191083/txn.txt)

**Comment by jolestar** [comment]
> > 当前有一些情况下，交易会一直是 pending 状态，只能通过重启或者删除插件来解决。建议优化一下错误处理的机制：
> > 
> > 1. 交易一旦生成，就应该能算出 hash，可以让用户在界面上看到 hash，这个对排查问题也很有用。不然用户反馈交易丢了，或者卡住了，但没有 hash，就很难排查是哪里的问题。
> 
> **这个hash如果有了的话，在交易详情弹窗里面是可以拷贝出来的，或者点击链接到浏览器** <img alt="image" width="347" src="https://user-images.githubusercontent.com/171268/156892655-303d51a8-731c-4ef7-a014-7417ba0b50ae.png">
> 
> > 2. 提交给交易池，调用 rpc 报错，根据错误分别处理，1. 交易无法通过验证，报客户端错误，标记为失败丢弃。2. 其他错误，比如服务不可用，ratelimit 限制，网络超时等，等待一段时间后重试。
> > 3. 如果重试超过一定的次数，则直接标记为失败（感觉也可以考虑给最新的一条失败交易增加一个人工重试的按钮？）。
> > 4. 有了重试机制后，会有一种特殊情况需要处理：超时的情况下，有可能交易已经被提交，并且打包，这种最后需要标记为成功。
> 
> **2/3/4的逻辑，在StarMask里面本身就已经都有了，但是前提是网络正常的时候才会生效，如果网络都没有了（vpn挂了） 那啥都不好使。**
> 
> > 如果有错误码不明确，RPC 这边一起定义修改。
> > **V3.8.0的交易详情弹窗里面加了个逻辑，如果是失败的交易，最下面有个链接，点击之后可以拷贝出交易的原始信息，方便用户发给开发者进行debug**
> 
> <img alt="image" width="342" src="https://user-images.githubusercontent.com/171268/156892761-640d4e00-0111-4476-b401-25065975dd88.png">

可以确认下，如果网络有问题，出现了 pending 状态，然后网络恢复后，能否自动恢复。看用户的描述貌似是不能自动恢复。
